import { describe, expect, it } from "vitest";
import { zipSync } from "fflate";
import { encode } from "fast-png";
import { convertPack, readZip } from "../src/index.js";
import { decodePng, sanitizePng } from "../src/image/png.js";

/**
 * Quirks of packs generated by ItemsAdder, all found in a real merged server
 * pack: textures published under atlas sprite aliases, PNGs whose zlib checksum
 * is wrong, and fractional mcmeta frametimes.
 */

function png(width = 16, height = 16, rgba: [number, number, number, number] = [255, 0, 0, 255]): Uint8Array {
  const data = new Uint8Array(width * height * 4);
  for (let i = 0; i < width * height; i++) data.set(rgba, i * 4);
  return new Uint8Array(encode({ width, height, data, channels: 4 }));
}

/** Corrupt the trailing adler32 of the IDAT stream, like IA's exporter does. */
function breakChecksum(bytes: Uint8Array): Uint8Array {
  const out = bytes.slice();
  const view = new DataView(out.buffer);
  let offset = 8;
  while (offset + 8 <= out.length) {
    const length = view.getUint32(offset);
    const type = String.fromCharCode(out[offset + 4]!, out[offset + 5]!, out[offset + 6]!, out[offset + 7]!);
    if (type === "IDAT") {
      // Last 4 bytes of the zlib stream are the adler32.
      const adlerAt = offset + 8 + length - 4;
      out[adlerAt] = out[adlerAt]! ^ 0xff;
      // Chunk CRC stays valid only if we recompute it; re-emit through pngChunk
      // is overkill here — fast-png checks the zlib data before the CRC.
      break;
    }
    offset += 12 + length;
  }
  return out;
}

function fixtureZip(files: Record<string, Uint8Array | string>): Uint8Array {
  const tree: Record<string, Uint8Array> = {};
  for (const [path, content] of Object.entries(files)) {
    tree[path] = typeof content === "string" ? new TextEncoder().encode(content) : content;
  }
  return zipSync(tree);
}

describe("ItemsAdder-generated packs", () => {
  it("decodes PNGs whose zlib checksum is invalid", () => {
    const broken = breakChecksum(png(8, 8, [10, 20, 30, 255]));
    const image = decodePng(broken);
    expect(image.width).toBe(8);
    expect([...image.data.slice(0, 4)]).toEqual([10, 20, 30, 255]);
    // sanitizePng rebuilds the file so the copy shipped to Bedrock is valid.
    const repaired = sanitizePng(broken);
    expect(repaired).not.toBe(broken);
    expect(decodePng(repaired).width).toBe(8);
    // A healthy PNG passes through untouched.
    const healthy = png(4, 4);
    expect(sanitizePng(healthy)).toBe(healthy);
  });

  it("resolves textures published under an atlas sprite alias", async () => {
    const zip = fixtureZip({
      "pack.mcmeta": JSON.stringify({ pack: { pack_format: 15 } }),
      // The model references `ia:7`, which only exists as an atlas alias.
      "assets/minecraft/atlases/blocks.json": JSON.stringify({
        sources: [{ type: "single", resource: "custom:item/blade", sprite: "ia:7" }],
      }),
      "assets/minecraft/models/item/diamond_sword.json": JSON.stringify({
        parent: "minecraft:item/handheld",
        textures: { layer0: "minecraft:item/diamond_sword" },
        overrides: [{ predicate: { custom_model_data: 3 }, model: "custom:item/aliased" }],
      }),
      "assets/custom/models/item/aliased.json": JSON.stringify({
        textures: { "0": "ia:7", particle: "ia:7" },
        elements: [
          {
            from: [4, 0, 4],
            to: [12, 16, 12],
            faces: { north: { uv: [0, 0, 8, 16], texture: "#0" } },
          },
        ],
      }),
      "assets/custom/textures/item/blade.png": png(16, 16, [200, 20, 20, 255]),
    });

    const result = await convertPack(zip, { packName: "Aliased" });
    const missing = result.report.entries.filter((e) => e.detail?.includes("magenta"));
    expect(missing).toEqual([]);
    const out = readZip(result.mcpack);
    const atlas = out.read("textures/geyser_custom/atlases/custom_item_aliased.png")!;
    // The alias target's colour, not the magenta placeholder.
    expect([...decodePng(atlas).data.slice(0, 4)]).toEqual([200, 20, 20, 255]);
  });

  it("accepts fractional mcmeta frametimes", async () => {
    const zip = fixtureZip({
      "pack.mcmeta": JSON.stringify({ pack: { pack_format: 15 } }),
      "assets/minecraft/models/item/diamond_sword.json": JSON.stringify({
        parent: "minecraft:item/handheld",
        textures: { layer0: "minecraft:item/diamond_sword" },
        overrides: [{ predicate: { custom_model_data: 4 }, model: "custom:item/animated" }],
      }),
      "assets/custom/models/item/animated.json": JSON.stringify({
        textures: { "0": "custom:item/strip", particle: "custom:item/strip" },
        elements: [
          {
            from: [4, 0, 4],
            to: [12, 16, 12],
            faces: { north: { uv: [0, 0, 8, 16], texture: "#0" } },
          },
        ],
      }),
      "assets/custom/textures/item/strip.png": png(16, 48, [20, 200, 40, 255]),
      "assets/custom/textures/item/strip.png.mcmeta": JSON.stringify({ animation: { frametime: 2.1 } }),
    });

    const result = await convertPack(zip, { packName: "Animated" });
    expect(result.report.entries.filter((e) => e.status === "error")).toEqual([]);
    expect(readZip(result.mcpack).has("models/entity/geyser_custom/custom_item_animated.geo.json")).toBe(true);
  });
});
